Update src/library/Text
targetx/fork-mineral-ui pull request #32
Opened 2019-06-24 22:44 UTC by tx-michael

2019-06-24 22:59 UTC, tx-trent approved these changes

2019-06-24 23:11 UTC, tx-nestor commented on src/library/Text/propTypes.js
> +  marginLeft: oneOfType([number, string]),
might as well add marginHorizontal since we're supporting all at this point

2019-06-24 23:13 UTC, tx-nestor requested changes

2019-06-24 23:13 UTC, tx-nestor commented on src/library/Text/propTypes.js
>    marginVertical: oneOfType([number, string]),
might as well add marginHorizontal since we're supporting all at this point

2019-06-25 20:44 UTC, tx-steven approved these changes

2019-06-25 20:59 UTC, tx-nestor requested changes

2019-06-25 20:59 UTC, tx-nestor commented on src/library/Text/styled.js
> +      ...(marginHorizontal && { marginHorizontal }),
This is wrong... look at how marginVertical is used below

2019-06-25 21:05 UTC, tx-nestor approved these changes

2019-06-25 21:14 UTC, closed without merging