Update src/library/Table
targetx/fork-mineral-ui pull request #39
Opened 2019-07-15 18:39 UTC by tx-michael

2019-07-15 18:40 UTC, tx-michael commented
used for https://github.com/targetx/td-core-web-ui/pull/7

2019-07-15 19:02 UTC, tx-steven approved these changes

2019-07-16 06:13 UTC, tx-nestor requested changes

2019-07-16 06:13 UTC, tx-nestor commented on src/library/Table/styled.js
> +    ...(verticalAlign && { verticalAlign })
verticalAlign is already being set above, so shouldn't this just be:
```
verticalAlign: verticalAlign || theme.TableCell_verticalAlign
```

2019-07-16 23:21 UTC, tx-nestor approved these changes

2019-07-17 16:28 UTC, merged