Update src/library/Button
targetx/fork-mineral-ui pull request #5
Opened 2019-05-23 18:08 UTC by tx-steven

Add custom prop to button:
`secondary` - Adds all styles necessary for secondary button.

2019-05-23 20:58 UTC, tx-trent approved these changes

2019-05-24 05:22 UTC, tx-nestor requested changes
@tx-steven  As we discussed yesterday, let's use the `variant` prop to implement this instead of `secondary` prop.
```jsx
<Button primary variant="grayscale" /> // solid button, gray color
<Button variant="grayscale" /> // hollow button, gray color
```

2019-05-24 21:43 UTC, tx-nestor requested changes

2019-05-24 21:43 UTC, tx-nestor commented on src/library/Button/constants.js
> +  greyscale: 'greyscale',
Let's stick with the American spelling `grayscale`. I think that's what's already being used my mineral-ui.

Also, where do we define the color ramp for it?

2019-05-24 22:40 UTC, tx-nestor approved these changes

2019-05-24 22:47 UTC, merged